build.gradle.kts, src/main/java/com/musai/musai/config/SecurityConfig.java, src/main/java/com/musai/musai/config/SwaggerConfig.java, src/main/java/com/musai/musai/entity/User.java, src/main/java/com/musai/musai/repository/UserRepository.java, src/main/java/com/musai/musai/service/UserService.java, src/main/resources/application.properties, src/test/java/com/musai/musai/UserRepositoryTest.java
스웨거 연동 및 mongoDB 연결 설정 Resolves #3
4
스웨거 연결 및 mongoDB 연결 설정
=> ✨Feat: Add 스웨거 연동

build.gradle.kts, src/main/java/com/musai/musai/config/SecurityConfig.java, src/main/java/com/musai/musai/config/WebConfig.java, src/main/java/com/musai/musai/controller/RecogController.java, src/main/java/com/musai/musai/dto/RecogRequestDTO.java, src/main/java/com/musai/musai/dto/RecogResponseDTO.java, src/main/java/com/musai/musai/service/RecogService.java, src/main/resources/application.properties
#1
작품 인식과 관련된 API 생성 및 AI 서버 연결했습니다!
=> ✨Feat: Add 작품 인식 api 생성

src/main/java/com/musai/musai/controller/RecogController.java, src/main/java/com/musai/musai/controller/SwaggerRedirectController.java, src/main/java/com/musai/musai/dto/RecogErrorDTO.java, src/main/java/com/musai/musai/dto/RecogResponseDTO.java, src/main/java/com/musai/musai/service/RecogService.java, src/main/resources/application.properties
#1
1. 응답 DTO 수정
2. 스웨거 경로 수정
3. 파일 업로드 용량 올림
=> ✨Feat/recogApi#1

Dockerfile
=> ✨Feat: Add 도커파일 생성

src/main/java/com/musai/musai/service/RecogService.java
#7 
도커 네트워크 생성에 따른 AI 서버 경로 수정
=> 🐛Feat/docker file#7

src/main/java/com/musai/musai/dto/RecogResponseDTO.java, src/main/java/com/musai/musai/service/RecogService.java
=> ✨Feat: Update 응답 DTO 수정

build.gradle.kts, src/main/java/com/musai/musai/controller/TtsController.java, src/main/java/com/musai/musai/dto/TtsRequestDTO.java, src/main/java/com/musai/musai/dto/TtsResponseDTO.java, src/main/java/com/musai/musai/service/TtsService.java
#11 
TTS 연결 수정 완료했습니다.
mp3 파일로 응답
=> ✨Feat: Update TTS 연결 수정

src/main/java/com/musai/musai/controller/RecogController.java, src/main/java/com/musai/musai/dto/RecogResponseDTO.java, src/main/java/com/musai/musai/service/RecogService.java
#19 
작품 인식시, 난이도별로 해설 제공하는 기능 추가했습니다!
타겟 이미지 이름이 같으면 뷰포리아에 등록이 안 되더라구요 그래도 괜찮겠죠?8ㅅ8
스웨거 연동 상태
=> ✨Feat: Add 난이도별 설명 추가

src/main/java/com/musai/musai/config/SecurityConfig.java, src/main/java/com/musai/musai/config/SwaggerConfig.java, src/main/java/com/musai/musai/controller/RecogController.java, src/main/java/com/musai/musai/controller/TtsController.java, src/main/java/com/musai/musai/controller/VuforiaController.java, src/main/java/com/musai/musai/controller/exhibition/ExhibitionController.java, src/main/java/com/musai/musai/jwt/JwtAuthenticationFilter.java, src/main/java/com/musai/musai/jwt/JwtTokenProvider.java
#25 
api 연결 시, jwt 토큰 인증하는 거 추가했습니다!
swagger 사이트에 Authorize 버튼 활성화
=> ✨Feat: Add JWT 토큰 인증 추가

src/main/java/com/musai/musai/controller/bookmark/BookmarkController.java, src/main/java/com/musai/musai/dto/bookmark/BookmarkDTO.java, src/main/java/com/musai/musai/entity/bookmark/Bookmark.java, src/main/java/com/musai/musai/repository/bookmark/BookmarkRepository.java, src/main/java/com/musai/musai/service/bookmark/BookmarkService.java
#31 
북마크 기능과 관련된 API 추가했습니다.
북마크 전체 조회, 북마크 상세 조회, 북마크 추가, 삭제 API
전체 조회 API 경로 이름 괜찮을까요?
북마크 추가 화면
북마크 전체 조회 화면
=> ✨Feat: Add 북마크 관련 API 추가

build.gradle.kts, src/main/java/com/musai/musai/config/SecurityConfig.java, src/main/java/com/musai/musai/controller/exhibition/ExhibitionController.java, src/main/java/com/musai/musai/controller/exhibition/TestApiController.java, src/main/java/com/musai/musai/dto/exhibition/ExhibitionDTO.java, src/main/java/com/musai/musai/entity/exhibition/ApiFetchStatus.java, src/main/java/com/musai/musai/entity/exhibition/Exhibition.java, src/main/java/com/musai/musai/jwt/JwtTokenProvider.java, src/main/java/com/musai/musai/repository/exhibition/ApiFetchStatusRepository.java, src/main/java/com/musai/musai/repository/exhibition/ExhibitionRepository.java, src/main/java/com/musai/musai/scheduler/ExhibitionScheduler.java, src/main/java/com/musai/musai/service/exhibition/ExhibitionService.java, src/main/java/com/musai/musai/util/ExhibitionApiParser.java, src/main/java/com/musai/musai/util/ExhibitionApiResponse.java, src/main/resources/application.properties
#24 
전시회 API에서 받아온 내용을 필터링하여 DB에 저장 완료했습니다.
=> ♻️ Add: Update 전시회 API DB 저장 완료

src/main/java/com/musai/musai/controller/exhibition/ExhibitionController.java, src/main/java/com/musai/musai/repository/exhibition/ExhibitionRepository.java, src/main/java/com/musai/musai/service/exhibition/ExhibitionService.java, src/main/resources/application.properties
ex) #24 
전시회 검색 API 추가했습니다.
'예술' 검색했을 때 나오는 전시회 목록
=> ✨Feat: Add 전시회 검색 API 추가

src/main/java/com/musai/musai/controller/exhibition/ExhibitionController.java, src/main/java/com/musai/musai/repository/exhibition/ExhibitionRepository.java, src/main/java/com/musai/musai/service/exhibition/ExhibitionService.java
#24 
전시관 검색 API 추가했습니다.
키워드 '중앙'으로 검색했을 때 검색 결과
=> ✨Feat: Add 전시관 검색 api 추가

src/main/java/com/musai/musai/controller/user/UserController.java
#40 
사용자 조회 및 설정에 관련한 API 경로 수정했습니다.
경로 수정
=> ♻️Ref: Update API 경로 수정

src/main/java/com/musai/musai/controller/AuthController.java, src/main/resources/application.properties
#42 
안드로이드 회원가입을 위한 웹 클라이언트 아이디를 추가했습니다.
=> ♻️Refac: Add 클라이언트 아이디 추가

src/main/java/com/musai/musai/controller/exhibition/ExhibitionController.java, src/main/java/com/musai/musai/scheduler/ExhibitionScheduler.java, src/main/java/com/musai/musai/service/exhibition/ExhibitionService.java
#24 
전시회 DB 업데이트 스케줄러 연결 추가했습니다.
=> ♻️Refac: Update 스케줄러 연결

src/main/java/com/musai/musai/entity/user/Setting.java, src/main/java/com/musai/musai/service/user/UserService.java
#42 
회원가입시, 설정 테이블 관련한 오류 수정했습니다.
=> 🐛Bug: Update 회원가입 오류 수정

src/main/java/com/musai/musai/service/difficulty/DifficultyService.java
=> ♻️ Feat: Update 작품 난이도 변경 주소 수정

.gitignore, build.gradle.kts, src/main/java/com/musai/musai/config/FirebaseConfig.java, src/main/java/com/musai/musai/controller/alarm/AlarmController.java, src/main/java/com/musai/musai/dto/alarm/AlarmDTO.java, src/main/java/com/musai/musai/entity/alarm/Alarm.java, src/main/java/com/musai/musai/entity/user/Token.java, src/main/java/com/musai/musai/repository/alarm/AlarmRepository.java, src/main/java/com/musai/musai/repository/alarm/TokenRepository.java, src/main/java/com/musai/musai/service/alarm/AlarmService.java
#52 
FCM을 이용한 토큰 저장 API 추가했습니다.
=> ✨Feat: Add 알림 토큰 저장 API 추가

src/main/java/com/musai/musai/entity/alarm/Alarm.java, src/main/java/com/musai/musai/entity/user/Setting.java, src/main/java/com/musai/musai/entity/user/Token.java, src/main/java/com/musai/musai/repository/alarm/AlarmRepository.java, src/main/java/com/musai/musai/repository/alarm/TokenRepository.java, src/main/java/com/musai/musai/repository/bookmark/BookmarkRepository.java
=> 🐛Bug: Update 알림 빌드 오류 수정

src/main/java/com/musai/musai/controller/alarm/AlarmController.java
#52 
알림 서비스 오류 해결
swagger 토큰 저장 테스트
=> 🐛Bug: Update 알림 서비스 오류 해결

src/main/java/com/musai/musai/controller/post/PostController.java, src/main/java/com/musai/musai/dto/post/PostDto.java, src/main/java/com/musai/musai/entity/post/Post.java, src/main/java/com/musai/musai/repository/post/PostRepository.java, src/main/java/com/musai/musai/service/post/PostService.java
#51 
커뮤니티 게시글 목록 조회, 상세 조회, 작성, 삭제, 수정 코드 추가하였습니다.
=> ✨ Feat: Add 커뮤니티 게시글 crud 추가

src/main/java/com/musai/musai/controller/community/CommentController.java, src/main/java/com/musai/musai/controller/community/PostController.java, src/main/java/com/musai/musai/dto/community/CommentDTO.java, src/main/java/com/musai/musai/dto/community/PostDTO.java, src/main/java/com/musai/musai/entity/community/Comment.java, src/main/java/com/musai/musai/entity/community/Post.java, src/main/java/com/musai/musai/repository/community/CommentRepository.java, src/main/java/com/musai/musai/repository/community/PostRepository.java, src/main/java/com/musai/musai/repository/ticket/TicketRepository.java, src/main/java/com/musai/musai/service/community/CommentService.java, src/main/java/com/musai/musai/service/community/PostService.java
#51 
댓글 기능과 관련된 API를 추가했습니다.
1. 댓글 작성 API
2. 댓글 수정 API
3. 댓글 삭제 API
4. 답글 구조를 고려한 계층형 및 페이징 처리 기능을 포함한 댓글 조회 API
작성한 댓글 목록
댓글 수정 가능
댓글 전체 목록
댓글 삭제
계층형 구조 및 페이징 처리한 댓글 조회 결과
=> ✨Feat: Add 댓글 관련 API 추가

src/main/java/com/musai/musai/controller/community/LikeController.java, src/main/java/com/musai/musai/controller/community/PostController.java, src/main/java/com/musai/musai/dto/community/LikeDTO.java, src/main/java/com/musai/musai/entity/community/Like.java, src/main/java/com/musai/musai/repository/community/LikeRepository.java, src/main/java/com/musai/musai/repository/community/PostRepository.java, src/main/java/com/musai/musai/service/community/LikeService.java, src/main/java/com/musai/musai/service/community/PostService.java
#51 
공감 추가/조회 기능 + 게시글 검색 기능 추가 했습니다
=> ✨ Feat: Add 공감 기능 + 게시글 검색 기능 추가

src/main/java/com/musai/musai/repository/community/PostRepository.java
#51 
PostRepository에 빠진 코드로 오류가 발생해 수정했습니다.
=> ✨ Feat: Add community 오류 수정

src/main/java/com/musai/musai/controller/alarm/AlarmController.java
#52 
스웨거 테스트 시, 알림 API 설명 추가했습니다.
추가된 설명
=> 💡Chore: 알림 API 설명 추가

src/main/java/com/musai/musai/controller/auth/AuthController.java, src/main/java/com/musai/musai/controller/recog/RecogController.java, src/main/java/com/musai/musai/controller/recog/VuforiaController.java, src/main/java/com/musai/musai/controller/swagger/SwaggerRedirectController.java, src/main/java/com/musai/musai/controller/tts/TtsController.java, src/main/java/com/musai/musai/dto/recog/RecogErrorDTO.java, src/main/java/com/musai/musai/dto/recog/RecogRequestDTO.java, src/main/java/com/musai/musai/dto/recog/RecogResponseDTO.java, src/main/java/com/musai/musai/dto/recog/VuforiaResponseDTO.java, src/main/java/com/musai/musai/dto/tts/TtsRequestDTO.java, src/main/java/com/musai/musai/dto/tts/TtsResponseDTO.java, src/main/java/com/musai/musai/service/recog/RecogService.java, src/main/java/com/musai/musai/service/recog/VuforiaService.java, src/main/java/com/musai/musai/service/tts/TtsService.java
#66 
파일 구조를 기능별로 수정했습니다.
정리된 파일 구조
=> ♻️Refac: Update 파일 구조 수정

build.gradle.kts, src/main/java/com/musai/musai/controller/ticket/ColorController.java, src/main/java/com/musai/musai/dto/ticket/ColorDTO.java, src/main/java/com/musai/musai/service/ticket/ColorService.java
#68 
티켓의 배경색을 위한 이미지 색 추천 API를 생성하였습니다.
=> ✨ Feat: Add 티켓 색 추천 API 구현

src/main/java/com/musai/musai/controller/community/PostController.java, src/main/java/com/musai/musai/dto/community/PostDTO.java, src/main/java/com/musai/musai/dto/community/PostRequestDTO.java, src/main/java/com/musai/musai/dto/community/PostUpdateDTO.java, src/main/java/com/musai/musai/repository/community/CommentRepository.java, src/main/java/com/musai/musai/service/community/CommentService.java, src/main/java/com/musai/musai/service/community/PostService.java
#51 
게시글 기능과 관련된 API를 수정했습니다.
1. 게시글 조회 시, 댓글 개수 반환하도록 수정
2. 게시글 작성 API 리퀘스트 바디값 간소화
3. 게시글 수정 API 리퀘스트 바디값 간소화
게시글 조회 시, 댓글 개수 반환
게시글 작성 및 수정 API RequestBody 값 수정
=> ✨Feat: Update 게시글 기능 관련 API 수정

src/main/java/com/musai/musai/config/AppConfig.java, src/main/java/com/musai/musai/controller/exhibition/ExhibitionController.java, src/main/java/com/musai/musai/dto/exhibition/DetailApiResponse.java, src/main/java/com/musai/musai/dto/exhibition/ExhibitionDTO.java, src/main/java/com/musai/musai/entity/exhibition/Exhibition.java, src/main/java/com/musai/musai/service/exhibition/ExhibitionService.java, src/main/java/com/musai/musai/util/DetailApiParser.java, src/main/java/com/musai/musai/util/ExhibitionApiParser.java
#24
place_url 컬럼 추가하고 api 호출하여 데이터 적재하는 코드 추가하였습니다
=> ✨ Feat: Add exhibition 테이블에 place_url 연동

src/main/java/com/musai/musai/controller/alarm/AlarmController.java, src/main/java/com/musai/musai/dto/alarm/AlarmDTO.java, src/main/java/com/musai/musai/repository/alarm/AlarmRepository.java, src/main/java/com/musai/musai/service/alarm/AlarmService.java, src/main/java/com/musai/musai/service/community/CommentService.java
#52 
커뮤니티와 관련된 알림 관련 개발했습니다.
1. 내 게시글에 댓글이 달릴 때 알림 발송
2. 내 댓글(답글)에 답글이 달릴 때 알림 발송
실제 기기에 온 알림
=> ✨Feat: Add 커뮤니티 알림 기능 추가

src/main/java/com/musai/musai/service/community/CommentService.java
#52 
답글의 답글의 조회가 안 되는 오류 수정했습니다.
리스트로 조회되는 것 확인
=> 🐛Bug: Update 답글의 답글 조회 오류 수정

src/main/java/com/musai/musai/controller/alarm/AlarmController.java, src/main/java/com/musai/musai/dto/alarm/AlarmDTO.java, src/main/java/com/musai/musai/entity/alarm/Alarm.java, src/main/java/com/musai/musai/repository/alarm/AlarmRepository.java, src/main/java/com/musai/musai/service/alarm/AlarmService.java
#52 
알림 기능 관련 API 추가 및 수정했습니다.
1. 알림 전체 삭제 API 추가
2. 특정 알림 삭제 API 추가
3. 알림 조회 시, 제목 및 내용 반환하도록 수정
알림 조회 시, 제목 및 내용 반환
특정 알림 삭제 
유저의 알림 전체 삭제
=> ✨Feat: Add 알림 기능 관련 API 추가

src/main/java/com/musai/musai/service/community/CommentService.java
ex) #1
댓글 작성 시, 답글 ID 검증 로직 추가했습니다.
해당 comment_id가 존재하지 않을 때 혹은 해당 게시글의 comment_id가 아닐 때는 오류 발생시키도록 했습니다.
존재하지 않는 parentCommentId일 시, 오류
오류 메시지
=> ✨Feat: Add 댓글 작성 시, 답글 검증 추가

src/main/java/com/musai/musai/controller/alarm/AlarmController.java
=> ♻️Refac: Update 알림 경로 수정

src/main/java/com/musai/musai/controller/ar/ARController.java, src/main/java/com/musai/musai/controller/recog/RecogController.java, src/main/java/com/musai/musai/dto/ar/ARRequestDTO.java, src/main/java/com/musai/musai/dto/ar/ARResponseDTO.java, src/main/java/com/musai/musai/dto/recog/RecogResponseDTO.java, src/main/java/com/musai/musai/service/ar/ARService.java, src/main/java/com/musai/musai/service/recog/RecogService.java, src/main/java/com/musai/musai/service/recog/VuforiaService.java
=> ✨Feat: Add AR 해설 API 추가

.gitignore, src/main/java/com/musai/musai/controller/arts/ArtController.java, src/main/java/com/musai/musai/controller/arts/MetController.java, src/main/java/com/musai/musai/dto/arts/ArtDto.java, src/main/java/com/musai/musai/dto/arts/MetDto.java, src/main/java/com/musai/musai/entity/arts/Art.java, src/main/java/com/musai/musai/entity/arts/Met.java, src/main/java/com/musai/musai/repository/arts/ArtRepository.java, src/main/java/com/musai/musai/repository/arts/MetRepository.java, src/main/java/com/musai/musai/service/arts/ArtService.java, src/main/java/com/musai/musai/service/arts/MetService.java
#82 
배치 문제와 방화벽 차단 문제를 해결했습니다.
=> ✨ Feat: Add MET API 코드 완성

src/main/java/com/musai/musai/service/alarm/AlarmService.java
#52 
스케줄러를 이용한 접속 유도 알림 추가했습니다.
기존의 allow_ralarm 필드 사용해 설정 확인했습니다.
=> ✨Feat: Add 접속 유도 알림 추가

src/main/java/com/musai/musai/service/recog/RecogService.java
=> 🐛Bug: Update 작품 인식 오류 수정

src/main/java/com/musai/musai/dto/bookmark/BookmarkDTO.java, src/main/java/com/musai/musai/entity/bookmark/Bookmark.java, src/main/java/com/musai/musai/service/bookmark/BookmarkService.java
=> 🔧Fix: Add 북마크 예술사조 추가

src/main/java/com/musai/musai/controller/preferenceRecommend/PreferenceRecommendController.java, src/main/java/com/musai/musai/dto/preferenceRecommend/PreferenceRecommendDTO.java, src/main/java/com/musai/musai/entity/preferenceRecommend/PreferenceRecommend.java, src/main/java/com/musai/musai/repository/arts/ArtRepository.java, src/main/java/com/musai/musai/repository/preferenceRecommend/PreferenceRecommendRepository.java, src/main/java/com/musai/musai/service/preferenceRecommend/PreferenceRecommendService.java
#93
사용자 별 사조 선호도 기반으로 작품 추천 시스템 개발 완료했습니다
=> ✨ Feat: Add 선호도 기반 추천 시스템 개발

src/main/java/com/musai/musai/controller/community/PostController.java, src/main/java/com/musai/musai/dto/community/ImageUploadResponseDTO.java, src/main/java/com/musai/musai/service/community/PostService.java
#101 
게시글 작성시, 이미지 업로드 API 추가했습니다.
추후에 S3 버킷 이름 바꿔야 할 것 같습니다!
스웨거 테스트 결과
=> ✨Feat: Add 게시글 이미지 업로드 API 추가
